/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Genesis' at '9/22/16 7:14 PM' with Gradle 2.13
 *
 * @author Genesis, @date 9/22/16 7:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
